#!/usr/bin/env bash
# Interactive .env bootstrap for khriss.
#
# Copies .env.example -> .env and fills it in, pre-seeding known values and
# prompting for the rest. Re-running it uses your current .env as the defaults,
# so it doubles as an "edit" flow. Secrets are read hidden and never echoed.
#
# The Shopify custom-app token (shpat_...) and API secret come from your store
# admin: Settings -> Apps and sales channels -> Develop apps -> your app ->
# API credentials. The CLI cannot mint these; paste them here.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

EXAMPLE=".env.example"
TARGET=".env"

[[ -f "$EXAMPLE" ]] || { echo "error: $EXAMPLE not found in $ROOT" >&2; exit 1; }

# Prefer existing .env as the source of defaults; fall back to the example.
SRC="$EXAMPLE"
if [[ -f "$TARGET" ]]; then
  echo "An existing .env was found; its values will be offered as defaults."
  SRC="$TARGET"
fi

# Read KEY=value defaults from $SRC into an associative array.
declare -A DEF
while IFS= read -r line; do
  [[ "$line" =~ ^[[:space:]]*# ]] && continue
  [[ "$line" == *=* ]] || continue
  k="${line%%=*}"; v="${line#*=}"
  DEF["${k// /}"]="$v"
done < "$SRC"

# ask VAR "Prompt text"  [--secret]
ask() {
  local var="$1" prompt="$2" secret="${3:-}" cur="${DEF[$1]:-}" ans
  if [[ "$secret" == "--secret" ]]; then
    local shown="(unset)"; [[ -n "$cur" ]] && shown="(keep existing)"
    read -r -s -p "$prompt $shown: " ans; echo
    ans="${ans:-$cur}"
  else
    read -r -p "$prompt [$cur]: " ans
    ans="${ans:-$cur}"
  fi
  RESULT="$ans"
}

echo
echo "=== Shopify (Dev Dashboard > your app > Parametres > Identifiants) ==="
ask SHOPIFY_SHOP           "Store domain (my-shoes.myshopify.com)";            SHOPIFY_SHOP="$RESULT"
ask SHOPIFY_API_VERSION    "Admin API version";                                SHOPIFY_API_VERSION="$RESULT"
ask SHOPIFY_CLIENT_ID      "Client ID";                                        SHOPIFY_CLIENT_ID="$RESULT"
ask SHOPIFY_CLIENT_SECRET  "Client secret" --secret;                           SHOPIFY_CLIENT_SECRET="$RESULT"
ask SHOPIFY_WEBHOOK_SECRET "API secret key (verifies products/update)" --secret; SHOPIFY_WEBHOOK_SECRET="$RESULT"

echo
echo "=== OpenRouter (LLM provider) ==="
ask OPENROUTER_API_KEY  "OpenRouter API key (sk-or-...)" --secret;  OPENROUTER_API_KEY="$RESULT"
ask OPENROUTER_BASE_URL "OpenRouter base URL";                     OPENROUTER_BASE_URL="$RESULT"
ask OPENROUTER_REFERER  "OpenRouter referer header (optional)";    OPENROUTER_REFERER="$RESULT"
ask OPENROUTER_TITLE    "OpenRouter title header (optional)";      OPENROUTER_TITLE="$RESULT"
ask RANKER_MODEL        "Ranker model slug";                       RANKER_MODEL="$RESULT"
ask VISION_MODEL        "Vision model slug (blank = reuse ranker)"; VISION_MODEL="$RESULT"
ask EXTRACTOR           "Extractor (clip | llm)";                  EXTRACTOR="$RESULT"

echo
echo "=== Datastores & serving ==="
ask QDRANT_URL                "Qdrant URL";                        QDRANT_URL="$RESULT"
ask QDRANT_API_KEY            "Qdrant API key (blank for local)";  QDRANT_API_KEY="$RESULT"
ask DATABASE_URL              "Postgres DSN";                      DATABASE_URL="$RESULT"
ask ALLOWED_ORIGINS           "Allowed CORS origins (comma-sep)";  ALLOWED_ORIGINS="$RESULT"
ask MODE_CONFIDENCE_THRESHOLD "Mode confidence threshold";         MODE_CONFIDENCE_THRESHOLD="$RESULT"

if [[ -f "$TARGET" ]]; then
  cp "$TARGET" "$TARGET.bak"
  echo "Backed up existing .env -> .env.bak"
fi

cat > "$TARGET" <<EOF
# Generated by scripts/setup-env.sh on $(date +%Y-%m-%d). Do not commit (gitignored).

# --- Shopify Admin API ---
SHOPIFY_SHOP=$SHOPIFY_SHOP
SHOPIFY_CLIENT_ID=$SHOPIFY_CLIENT_ID
SHOPIFY_CLIENT_SECRET=$SHOPIFY_CLIENT_SECRET
SHOPIFY_API_VERSION=$SHOPIFY_API_VERSION
SHOPIFY_WEBHOOK_SECRET=$SHOPIFY_WEBHOOK_SECRET

# --- OpenRouter ---
OPENROUTER_API_KEY=$OPENROUTER_API_KEY
OPENROUTER_BASE_URL=$OPENROUTER_BASE_URL
OPENROUTER_REFERER=$OPENROUTER_REFERER
OPENROUTER_TITLE=$OPENROUTER_TITLE
RANKER_MODEL=$RANKER_MODEL
VISION_MODEL=$VISION_MODEL
EXTRACTOR=$EXTRACTOR

# --- Datastores ---
QDRANT_URL=$QDRANT_URL
QDRANT_API_KEY=$QDRANT_API_KEY
DATABASE_URL=$DATABASE_URL

# --- Serving / behaviour ---
ALLOWED_ORIGINS=$ALLOWED_ORIGINS
MODE_CONFIDENCE_THRESHOLD=$MODE_CONFIDENCE_THRESHOLD
EOF

chmod 600 "$TARGET"
echo
echo "Wrote $TARGET (chmod 600)."
echo "Sanity check (secret values masked to first 4 chars):"
grep -E '^[A-Z]' "$TARGET" | sed -E 's/=(.{0,4}).+/=\1.../'
